name: KNIME LABS CI
on: [push]

jobs:
  unit-tests:
    name: Nodes Unit Tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: knime-understat-nodes-env
          environment-file: environment.yml
      - name: Lint Tests
        shell: bash -l {0}
        run: make lint
      - name: Unit Tests
        shell: bash -l {0}
        run: make unit
  build-nodes:
    name: Build KNIME Extension
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Create conda environment
        shell: bash -l {0}
        run: make create/builder
      - name: Build extension
        shell: bash -l {0}
        run: make build
